version: '3'
services:
  app:
    build: .
    ports:
      - 3000:80
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

  e2e:
    container_name: e2e-testing
    build:
      context: .
      dockerfile: e2e/Dockerfile
    depends_on:
      - "app"
    command: npx cypress run

volumes:
  node_modules: